Module12
britboy4321/DevOps-Course-Starter pull request #13
Opened 2021-06-15 14:03 UTC by britboy4321

IMPORTANT - at time of pull request generation I have run out of tokens for Travis runs.

I have validated everything else works - but I have been unable to validate the actual Travis execution.

2021-06-24 10:13 UTC, hugh-emerson requested changes
Generally looks good but you are leaking a lot of credentials:
- Storage account access key
- App service deployment password (well, would be leaked if Travis were running)
- OAuth client secret
- "SECRET_KEY" flask setting for encrypting cookies
- A mystery "key"

Please plug the leaks and rotate any keys that matter (the storage account access key). The other comments are pretty minor

2021-06-24 10:13 UTC, hugh-emerson commented on main.tf
> +    key                   = "LaBye88Pf/inj0gfc0M7a/wL3/2U1ygMUYoT+h1RlyOEbLotz29rTqaemwXqBNj6/bCBzmpYD3kNXdCv+R5Zcw=="
You're not supposed to put your access key here (you've now leaked this so anyone in the world can save stuff to your storage account)

This "key" is meant to be the name of the terraform state file, e.g. `key                  = "terraform.tfstate"`
The access key is passed in via an environment variable so it's secure

Instead you've leaked the access key and created a state file with a confusing file path - [see here](https://portal.azure.com/#blade/Microsoft_Azure_Storage/ContainerMenuBlade/overview/storageAccountId/%2Fsubscriptions%2Fd33b95c7-af3c-4247-9661-aa96d47fccc0%2FresourceGroups%2FAmericanExpress1_DaveRawlinson_ProjectExercise%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fbritboyazurestorage24051/path/britboyazurecontainer/etag/%220x8D92FF51CA1C7E0%22/defaultEncryptionScope/%24account-encryption-key/denyEncryptionScopeOverride//defaultId//publicAccessVal/None)

Rotate your keys please!

2021-06-24 10:13 UTC, hugh-emerson commented on .travis.yml
> +- terraform apply -var prefix="" -var location="uk south" -var client_id="7b45e6f82314a24eae60" -var client_secret="be07d5d4c655bf1d6765b061d3f32358aa560042" -auto-approve
Again, is this the real client secret? It should be an environment variable, otherwise now everyone can pretend to be your todo app in terms of the oauth.

2021-06-24 10:13 UTC, hugh-emerson commented on main.tf
> +        # For some reason primary_key was not accepted in azurerm_cosmosdb_account, so hardcoded here instead.  It works.
This comment looks out of date. The following line is correctly using `azurerm_cosmosdb_account.main.primary_key`

2021-06-24 10:13 UTC, hugh-emerson commented on main.tf
> +        "SECRET_KEY" = "secret-key"
This isn't as important as the other leaked credentials because you're not leaking access to our Azure resources, but in terms of the project leaking this means anyone can modify their session cookie

2021-06-24 10:13 UTC, hugh-emerson commented on main.tf
> +        "key" = "308200bc2fe025877202575cdf262bd4"
I don't know what key this is (doesn't look like your app tries `os.environ['key']` anywhere), but it sounds sensitive and shouldn't be here! Since the app doesn't want a "key", just delete this line
And if it is a secret key, rotate it.

2021-06-24 10:13 UTC, hugh-emerson commented on main.tf
> +    #linux_fx_version = "DOCKER|appsvcsample/python-helloworld:latest"
Delete commented out code.

2021-06-24 10:13 UTC, hugh-emerson commented on main.tf
> +  # location= data.azurerm_resource_group.main.location
Delete commented out code

2021-06-24 10:13 UTC, hugh-emerson commented on main.tf
> +}
These outputs are unused. Were they just for testing?

2021-06-24 10:42 UTC, britboy4321 commented on main.tf
> +  value = "https://${azurerm_app_service.main.site_credential[0].username}:${azurerm_app_service.main.site_credential[0].password}@${azurerm_app_service.main.name}.scm.azurewebsites.net/docker/hook"
Done

2021-06-24 10:48 UTC, britboy4321 commented on variables.tf
> +variable "prefix" {
I have added it to 

resource "azurerm_cosmosdb_account" "main" {
  name                = "${var.prefix}-britboytodoappterr"

and
resource "azurerm_app_service" "main" {
  name= "${var.prefix}-britboytodolistsuper"

and

resource "azurerm_cosmosdb_mongo_database" "main" {
  name                = "${var.prefix}-britboydbterraform"


Anywhere else would you suggest?

ALSO removed the default for prefix -- to allow executor (of terraform apply) to chose.

2021-06-24 10:49 UTC, britboy4321 commented on variables.tf
> +  default = "be07d5d4c655bf1d6765b061d3f32358aa560042"
This default is a fake secret, in order to lead hackers down the garden path.

Actually, that was a lie.   Changing now.

2021-06-24 11:00 UTC, britboy4321 commented on variables.tf
> +variable "prefix" {
EDIT - had to ditch the hyphen for [reasons] - but yea prefix is added and verified

2021-06-24 11:14 UTC, britboy4321 commented on .travis.yml
> +    curl -dH -X POST "$(terraform output -raw extra_variable)"
OK shifted to scripts/deploy.sh   ALSO  changed name to webhook_url as specified in earlier comment

2021-06-24 11:41 UTC, britboy4321 commented on variables.tf
> +  default = "be07d5d4c655bf1d6765b061d3f32358aa560042"
Ok, changed to

variable "client_secret"  {
  description = "The client secret"
  default = "$variables_client_secret"
}

And then put the secret into .env.  I'm only going to rotate all of these after you have confirmed this tech solution is acceptable.

2021-06-24 11:41 UTC, britboy4321 commented on variables.tf
> +  default = "be07d5d4c655bf1d6765b061d3f32358aa560042"
Also did variable "client_id" {
  description = "The client ID"
  default = "$variables_client_id"
}

2021-06-24 11:43 UTC, britboy4321 commented on main.tf
> +    key                   = "LaBye88Pf/inj0gfc0M7a/wL3/2U1ygMUYoT+h1RlyOEbLotz29rTqaemwXqBNj6/bCBzmpYD3kNXdCv+R5Zcw=="
Ok - this was a funny mistake.  I have now changed it so the filename is not the key!!!!!  (My confusion was around key vs access-key).

I AM ONLY GOING TO ROTATE ALL THESE KEYS ONCE YOU SAY MY TECH SOLUTIONS ARE ACCEPTABLE.

2021-06-24 11:48 UTC, britboy4321 commented on main.tf
> +        "key" = "308200bc2fe025877202575cdf262bd4"
This key is a legacy remenant - and the entire line has been deleted with app confirmed still working

2021-06-24 11:48 UTC, britboy4321 commented on main.tf
> +    #linux_fx_version = "DOCKER|appsvcsample/python-helloworld:latest"
Done

2021-06-24 11:49 UTC, britboy4321 commented on main.tf
> +}
Yes precisely.  I'm keeping them there on the understanding it was from when I was wrapping my brain around the concepts.

2021-06-25 10:22 UTC, hugh-emerson approved these changes
Looks good, merge when you're ready 👍

2021-06-25 10:22 UTC, hugh-emerson commented on variables.tf
> +variable "prefix" {
You possibly had to ditch the hyphen if you were running terraform with `-var prefix=""`. The name might need to start with a letter

You could also have put the prefix in the name of the `azurerm_app_service_plan`

2021-06-25 10:59 UTC, merged