Module7
britboy4321/DevOps-Course-Starter pull request #6
Opened 2021-02-09 12:12 UTC by britboy4321

Trying to merge master to try and get Travis to actually activate as otherwise it fails

2021-02-09 12:13 UTC, britboy4321 commented
For travis operation

2021-02-22 11:47 UTC, JackMead approved these changes
Looks good, I'm happy with this. Thanks for the detailed comments in your submission, they're really useful context!

I've left a couple of thoughts on things we could change, and in particular I think your secure environment variable is being ignored (though it's unused, so no harm there) which will likely need to be fixed when you add more tests, but I can see that travis is passing your tests currently

2021-02-22 11:47 UTC, JackMead commented on Dockerfile
> +# ALTERNATIVE -- KEPT HERE FOR A COUPOLE OF RELEASES IN CASE I NEED IT IN FUTURE
Normally I'd say ditch these and keep them in git but I saw your submission comments - it's really useful to know this is intentional, so more than happy to leave these here.

2021-02-22 11:47 UTC, JackMead commented on Dockerfile
> +RUN apt-get update
Worth noting, though it's not necessary to action, that this means we install chrome & the chromedriver on all of our images - so e.g. the prod image is larger because of this. Ideally we'd only install these on the test image (though that might require then refactoring how we copy the code across, since we want that to happen as late as possible to make the images quick to build)

2021-02-22 11:47 UTC, JackMead commented on .travis.yml
> +- FLASK_ENV=development
We can specify to Travis that these are environment variables and set these under env->global like the secure variable as follows:

```
env:
    global:
        - FLASK_ENV=development
        - FLASK_APP=todo_app/app
        - secure: DADAFCAASDA...
```

2021-02-22 11:47 UTC, JackMead commented on .travis.yml
> +    secure: DSTcbnI+O2YFJSj1FhP7zDlXwjJs4gFl5t7AupgP2efbw5EqPgnnfkgfKQ9fuBr/GtqIrRCwM9i8aLhQxtGbELdknokH+lPrkaHNHBJ0BmMj469ehYDzrmNS2WQu4KdNmEWTck+BUnW0sG1+AlGYN7Mg1LnqLdxYbDbgb/KaWzFfv6OQKstpCk3sjps
I notice that the log doesn't mention that it's setting any environment variable due to this, there's some details [here](https://docs.travis-ci.com/user/encryption-keys/) on how it reads the secure variables and you may want to prefix the secure line with a `-` i.e.
```
env:
  global:
    - secure: DSTcbnI...
 ```

2021-02-22 11:47 UTC, JackMead commented on README.md
> +# Docker Container :  To do list
Really nice detailed instructions, thanks

2021-03-31 13:31 UTC, hugh-emerson requested changes
So close but I'm afraid you've committed a password instead of passing it to Travis with an env var. That needs to be fixed. Otherwise it's looking good. My other two comments are minor.

Also, you seem to have pushed your module 8 work to this module 7 branch. In future try to work on a new branch and open a new pull request for each module.

2021-03-31 13:31 UTC, hugh-emerson commented on .travis.yml
> +- docker login --username=drawlinson48@gmail.com --password=12d12e9c-c546-498f-9bdb-5c8911cf27ec registry.heroku.com
You shouldn't include passwords in your (public!) codebase. You should change this to log in the same way as your other "docker login" command on line 9.

2021-03-31 13:31 UTC, hugh-emerson commented on .travis.yml
> +- docker push $DOCKERHUB_USERNAME/todoapp
You don't really want to push a new "latest" image to Docker Hub whenever you run tests. It would make more sense for "latest" to mean the latest version pushed to master. So you could move this into a `before_deploy:` section instead of this `script:` section.

2021-03-31 13:31 UTC, hugh-emerson commented on Dockerfile
> +ENTRYPOINT "poetry run flask run --host=0.0.0.0:$PORT"
You should either add a default value with `ENV PORT=5000` or update your README.md to mention that .env needs to include PORT to run the docker containers.

2021-04-13 14:11 UTC, merged